# Generated by Django 4.0.4 on 2022-06-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_alter_paginas_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paginas',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='imagenes'),
        ),
    ]
