# Generated by Django 4.0.4 on 2022-06-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0006_alter_paginas_cuerpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paginas',
            name='cuerpo',
            field=models.TextField(),
        ),
    ]
