# Generated by Django 4.0.4 on 2022-06-14 22:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0010_paginas_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginas',
            name='puntaje',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paginas',
            name='puntaje_promedio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='paginas',
            name='tstamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paginas',
            name='votos',
            field=models.IntegerField(default=0),
        ),
    ]
