# Generated by Django 4.0.4 on 2022-06-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0011_paginas_puntaje_paginas_puntaje_promedio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tstamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'seccion',
                'verbose_name_plural': 'secciones',
            },
        ),
        migrations.AddField(
            model_name='paginas',
            name='secciones',
            field=models.ManyToManyField(to='paginas.secciones'),
        ),
    ]
