# Generated by Django 4.0.4 on 2022-06-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0012_secciones_paginas_secciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='secciones',
            name='habilitada',
            field=models.BooleanField(default=False),
        ),
    ]
