# Generated by Django 4.0.4 on 2022-06-29 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0013_secciones_habilitada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paginas',
            name='puntaje_promedio',
        ),
    ]
