# Generated by Django 4.0.4 on 2022-06-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiles',
            name='tipo',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
