# Generated by Django 4.0.5 on 2022-06-28 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0003_perfiles_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiles',
            name='apellidos',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
