# Generated by Django 4.0.5 on 2022-06-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0004_perfiles_apellidos_alter_perfiles_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiles',
            name='habilitado',
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='tipo',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
