# Generated by Django 4.0.5 on 2022-06-28 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfiles', '0005_remove_perfiles_habilitado_alter_perfiles_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiles',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='perfiles', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
